---
name: Test
on: [push, pull_request]

jobs:
  lint:
    name: Rubocop
    timeout-minutes: 15
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.5"
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop

  ruby:
    name: Ruby ${{ matrix.ruby }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        redis: ["6.2"]
        ruby: ["3.2", "3.1", "3.0", "2.7", "2.6", "2.5", "jruby-9.3.6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache redis build
        uses: actions/cache@v3
        with:
          path: tmp/cache
          key: "local-tmp-cache-${{ matrix.redis }}-on-${{ matrix.os }}"
      - name: Lower system timeout
        run: sudo sysctl -w net.ipv4.tcp_syn_retries=2
      - name: Test
        run: |
          bundle exec rake ci
        env:
          EXT_PEDANTIC: "1"
          REDIS: ${{ matrix.redis }}

  redis:
    name: Redis ${{ matrix.redis }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        redis: ["7.0"]
        ruby: ["3.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache redis build
        uses: actions/cache@v3
        with:
          path: tmp/cache
          key: "local-tmp-cache-${{ matrix.redis }}-on-${{ matrix.os }}"
      - name: Lower system timeout
        run: sudo sysctl -w net.ipv4.tcp_syn_retries=2
      - name: Test
        run: |
          bundle exec rake ci
        env:
          EXT_PEDANTIC: "1"
          REDIS: ${{ matrix.redis }}

  # Redis sentinel is super slow to setup nad very flaky
  # So we run them independently against a single set of versions
  # so that they're easier to retry and less likely to flake.
  sentinel:
    name: Sentinel
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        redis: ["6.2"]
        ruby: ["3.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache redis build
        uses: actions/cache@v3
        with:
          path: tmp/cache
          key: "local-tmp-cache-${{ matrix.redis }}-on-${{ matrix.os }}"
      - name: Lower system timeout
        run: sudo sysctl -w net.ipv4.tcp_syn_retries=2
      - name: Test
        run: |
          bundle exec rake test:sentinel
        env:
          EXT_PEDANTIC: "1"
          REDIS: ${{ matrix.redis }}
